[Feature] 공통 컴포넌트인 단잠 스위치를 구현합니다.
no1msh/Danjam pull request #23
Opened 2024-06-20 19:20 UTC by librarywon

## AS-IS
재사용 가능성이 높아보이는 스위치를 프로젝트에 사용할 수 있도록 

## TO-BE
공통 단잠 스위치 컴포넌트로 구현하였습니다.

## KEY-POINT
material switch가 내부 원(thumb)의 크기가 조절이 안되는 이유로 직접 구현을 하였습니다.

offset을 이용하여 스위치 전환되는 효과를 구현하였습니다, 색상변경 가능성을 생각하여 디폴트 값으로 지금 쓰이는 값을 넣어두고 색상을 변경할 수 있도록 하였습니다.

상단에 상수화도 시켜두었는데 이런식으로 작성하는 것이 맞는지 호이스팅은 잘 이루어졌는지 확인해주시면 감사 드리겠습니다.

2024-06-21 05:35 UTC, no1msh requested changes
### 첫 pr 고생했습니다! 

몇 가지 코멘트 남겨드렸으니 확인후 다시 리뷰요청 부탁드립니다.

컴포넌트를 만드는 경험을 하니 어떠셨나요?
개인적으론 컴포넌트를 만드는게 컴포즈의 꽃이라고 생각합니다.
잘만들어둔 컴포넌트를 재사용을 하면서 UI 개발의 생산성이 증가한걸 체감한다면
재미도 많이 느끼곤 합니다.🤩

> ps. 제가 원하는건 thumb가 애니메이션으로 자연스럽게 움직이길 바랍니다. ㅎ
> 하지만 이건 추후에 추가해보시죠ㅎㅎ

2024-06-21 05:35 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +private val THUMB_OFFSET = 10.dp
compose에서 어떻게 이런 매직넘버를 상수화 할 수 있을까 고민이 많이 될거라 생각합니다.

몇 가지 질문을 드릴테니 다시 생각해보고 말씀해주세요.
1. val 과 const val의 차이는 무엇일까요?
2. `Int.dp`는 Dp객체로 반환을 해주는데, Dp객체는 어떻게 구현 되어있을까요?
3. Dp 객체는 생성을 할 때 오버헤드가 클까요?

추가로 컴포즈 라이브러리 개발에 있어서 상수 네이밍 컨벤션이 좀 색다릅니다.
하지만, 기존 상수 네이밍 컨벤션이 깊게 자리하고 있다면 변경 보단 그냥 쓰는것도 추천합니다.
다만 compose library에선 필수로 지키기를 권장하긴 합니다.
우린 라이브러리가 아닌 프로덕트에 들어갈 컴포넌트들을 정의하는 과정이니 팀 간의 협의하에 컨벤션을 정해도 괜찮을 것 같네요.
[참고](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#singletons_constants_sealed-class-and-enum-class-values)

2024-06-21 05:35 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +) {
지금처럼 컴포저블 함수에 `default argument`를 정의해주면
사용하는 입장에서 모든 인자를 다 넘기는 불편함이 해소되고, 필요시 `named argument`로 명시하며 원하는 인자를 넣을 수 있는 유연한 UI 개발이 될 수 있도록 구현할 수 있습니다. 👍

2024-06-21 05:35 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +    var isChecked by remember { mutableStateOf(checked) }
인자로 부터 들어온 `체크된 상태`를 지금 처럼 따로 state로 관리를 해주지 않고 그대로 사용한다면 어떻게 될까요?

2024-06-21 05:35 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +}
다양한 시나리오의 Switch 상태에 대해 테스트코드 처럼 preview를 작성해주셨네요. 👍
다만 preview에서 좀 더 실제 사용하는 것처럼 스위치를 누르면  boolean값이 바뀌어 모양이 달라지는 걸 테스트 해보려면 어떻게 해야할까요?
> preview에는 interaction을 테스트하는 모드가 있습니다.

2024-06-21 05:35 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +}
`@Preview` 어노테이션에 들어갈 수 있는 인자는 어떤 것들이 있을까요?

2024-06-21 05:35 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +package com.saeongjima.designsystem.component.switch
현재 스위치 클릭시 리플효과가 스위치를 감싸는 박스모양으로 각져있습니다.

스위치 모양 그대로 둥글게 리플효과를 적용하려면 어떻게 해야할까요?

2024-06-23 07:28 UTC, librarywon reviewed
저도 역시 이번에 컴포넌트를 만들고 확장성있게 어떻게 하면 남들도 잘 사용할 수 있을지 고민하면서 재밌었던 것 같습니다.

xml에서는 상상도 못할 작업들을 컴포즈에서 쉽게 작업하니까 너무 재밌네요 코드리뷰 반영했으니 확인 부탁드립니다

2024-06-23 07:28 UTC, librarywon commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +package com.saeongjima.designsystem.component.switch
clip이라는 기능이 있었군요...! 이런 디테일 넘치는 코드가 있다니

2024-06-23 07:28 UTC, librarywon commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +}
아 이것은 많이 공부해보았습니다
- 다크모드
- 그룹
- locate
- 화면 크기
- 상태바 활성화
- 디바이스
- 그 새로 업데이트된 다이나믹 컬러도 적용이 가능하더라구요

2024-06-23 07:28 UTC, librarywon commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +    var isChecked by remember { mutableStateOf(checked) }
상태 호이스팅을 사용하여 상태를 상위 컴포넌트에서 관리하게 만들어줄 수 있고 스위치 컴포넌트는 상태를 넘겨받은 상태만 사용할 것 같습니다.

제가 구현하려는 재사용 가능한 공통 컴포넌트는 이 방향성이 맞는 것 같구요

2024-06-23 07:28 UTC, librarywon commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +}
호이스팅을 시키니 눌러도 반응하지 않는 결과를 보았습니다. 당연히 상위 컴포넌트에서 state를 관리하고 있지 않으니 일어나는 현상이였고 각 프리뷰에 swtichState를 추가해 테스트 할 수 있도록 처리하였습니다.

2024-06-23 14:17 UTC, no1msh approved these changes
제 의도에 맞게 개선 잘하셨습니다!
LGTM!

2024-06-23 14:17 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +}
굿!
이렇게 하면 프리뷰 단계에서도 상태 변화에 따른 컴포저블 함수의 변경사항을 확인해 볼 수 있습니다.

2024-06-23 14:17 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +const val thumbOffset = 10
접근 제한자를 명시해주지 않은 이유가 있을까요?

2024-06-23 14:23 UTC, no1msh commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +private val THUMB_OFFSET = 10.dp
1 코딩에 명확한 정답은 없다고 생각하지만, `const val`와 `val`의 차이, Dp객체를 생성하는데 오버헤드가 있을지를 비교하여 본다면 숫자는 `const val`로 정의하고 `.dp`를 써주면서 사용하는게 조금이라도 더 최적화된 방식이 아닐까 생각했습니다.

2024-06-23 14:56 UTC, librarywon commented on core/designsystem/src/main/java/com/saeongjima/designsystem/component/switch/DanjamSwtich.kt
> +const val thumbOffset = 10
아 아닙니다 private을 붙여주는 것이 맞고 const val 과 val을 고민하다가 빼먹은 것 같네요 ㅋㅋㅋㅋ

2024-06-23 14:59 UTC, merged